# this sets up the Connect layer
version: '3.7'

# admin-bind is set to 0.0.0.0 to make control from the host easier
# it should be disabled for real topologies

services:
  dc1-client1-ping:
    network_mode: 'service:dc1-client1-pod'
    depends_on:
      - dc1-client1
    image: rboyer/pingpong:latest
    init: true
    command:
      - '-bind'
      # - '127.0.0.1:8080'
      - '0.0.0.0:8080'
      - '-dial'
      - '127.0.0.1:9090'

  dc1-client1-ping-sidecar:
    network_mode: 'service:dc1-client1-pod'
    depends_on:
      - dc1-client1-ping
    image: local/consul-envoy
    init: true
    restart: on-failure
    volumes:
      - './cache:/secrets:ro'
      - './sidecar-boot.sh:/bin/sidecar-boot.sh:ro'
    command:
      - '/bin/sidecar-boot.sh'
      - '-boot-token-file'
      - '/secrets/service-token--ping.val'
      #################
      - '-sidecar-for'
      - 'ping'
      - '-admin-bind'
      # for demo purposes
      - '0.0.0.0:19000'
      # debug
      - '--'
      - '-l'
      - 'trace'

  dc1-client2-pong:
    network_mode: 'service:dc1-client2-pod'
    depends_on:
      - dc1-client2
    image: rboyer/pingpong:latest
    init: true
    command:
      - '-bind'
      # - '127.0.0.1:8080'
      - '0.0.0.0:8080'
      - '-dial'
      - '127.0.0.1:9090'

  dc1-client2-pong-sidecar:
    network_mode: 'service:dc1-client2-pod'
    depends_on:
      - dc1-client2-pong
    image: local/consul-envoy
    init: true
    restart: on-failure
    volumes:
      - './cache:/secrets:ro'
      - './sidecar-boot.sh:/bin/sidecar-boot.sh:ro'
    command:
      - '/bin/sidecar-boot.sh'
      - '-boot-token-file'
      - '/secrets/service-token--pong.val'
      #################
      - '-sidecar-for'
      - 'pong'
      - '-admin-bind'
      # for demo purposes
      - '0.0.0.0:19000'
      # debug
      - '--'
      - '-l'
      - 'trace'
